services:
  hs:
    build: .
    env_file: ".env"
    ports:
      - "8000:8000"
  db:
    image: "postgres:bookworm"
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: