services:
  db:
    image: "postgres:bookworm"
    env_file: ".env"
    restart: "unless-stopped"
    ports:
      - "5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"
  homepage:
    container_name: glance
    image: glanceapp/glance
    ports:
      - "3000:3000"
    volumes:
      - "./config:/app/config"
volumes:
  db_data:
