services:
  db:
    image: "postgres:bookworm"
    env_file: ".env"
    restart: "unless-stopped"
    ports:
      - "5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"
  homepage:
    image: "ghcr.io/gethomepage/homepage:latest"
    ports:
      - "3000:3000"
    volumes:
      - "homepage_data:/app/config"
volumes:
  db_data:
  homepage_data: